// Generated by CoffeeScript 1.4.0
(function() {

  describe('jasmine-arguments-base', function() {
    return describe('matchers can be stacked so they', function() {
      it('should be false if no matcher is set', function() {
        return expect(jasmine.Arg().jasmineMatches("")).toBeFalsy();
      });
      it('should be able to evaluate a single matcher', function() {
        var matcher;
        matcher = jasmine.Arg().is(true);
        return expect(matcher.jasmineMatches(true)).toBeTruthy();
      });
      it('should be able to create an AND between a true and false matcher ( = false)', function() {
        var matcher;
        matcher = jasmine.Arg().is(true).is(false);
        return expect(matcher.jasmineMatches(true)).toBeFalsy();
      });
      return it('should all be called until one result is false', function() {
        var matcher;
        matcher = jasmine.Arg();
        spyOn(matcher, 'addMatcher').andCallThrough();
        matcher.isTruthy().isTruthy().isTruthy().jasmineMatches(true);
        return expect(matcher.addMatcher.calls.length).toEqual(3);
      });
    });
  });

}).call(this);
